# Generated by Django 5.2.1 on 2025-06-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
